version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.4
        environment:
          COVERALLS_SERVICE_NAME: circleci
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json"}}
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json"}}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm run lint && npm test && npm run codecov
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store-artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
